//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopClient.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopClient.Resources.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string strAdd {
            get {
                return ResourceManager.GetString("strAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Car.
        /// </summary>
        public static string strAddNewCar {
            get {
                return ResourceManager.GetString("strAddNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Results.
        /// </summary>
        public static string strBackToResults {
            get {
                return ResourceManager.GetString("strBackToResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string strBookNow {
            get {
                return ResourceManager.GetString("strBookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand: .
        /// </summary>
        public static string strBrand_ {
            get {
                return ResourceManager.GetString("strBrand:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Български.
        /// </summary>
        public static string strBulgarian {
            get {
                return ResourceManager.GetString("strBulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgas.
        /// </summary>
        public static string strBurgas {
            get {
                return ResourceManager.GetString("strBurgas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity: .
        /// </summary>
        public static string strCapacity_ {
            get {
                return ResourceManager.GetString("strCapacity:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string strCargo {
            get {
                return ResourceManager.GetString("strCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string strCars {
            get {
                return ResourceManager.GetString("strCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available cars found!.
        /// </summary>
        public static string strCarsNotFound {
            get {
                return ResourceManager.GetString("strCarsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Consumation: .
        /// </summary>
        public static string strConsumation_ {
            get {
                return ResourceManager.GetString("strConsumation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        public static string strDateOfBirth_ {
            get {
                return ResourceManager.GetString("strDateOfBirth:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string strDays {
            get {
                return ResourceManager.GetString("strDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days:.
        /// </summary>
        public static string strDays_ {
            get {
                return ResourceManager.GetString("strDays:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop off.
        /// </summary>
        public static string strDropOff {
            get {
                return ResourceManager.GetString("strDropOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Cars.
        /// </summary>
        public static string strECars {
            get {
                return ResourceManager.GetString("strECars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string strEmail_ {
            get {
                return ResourceManager.GetString("strEmail:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string strEnglish {
            get {
                return ResourceManager.GetString("strEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string strFirstName_ {
            get {
                return ResourceManager.GetString("strFirstName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path:.
        /// </summary>
        public static string strImagePath_ {
            get {
                return ResourceManager.GetString("strImagePath:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid brand..
        /// </summary>
        public static string strInvalidBrand {
            get {
                return ResourceManager.GetString("strInvalidBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid capacity..
        /// </summary>
        public static string strInvalidCapacity {
            get {
                return ResourceManager.GetString("strInvalidCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid consumation..
        /// </summary>
        public static string strInvalidConsumation {
            get {
                return ResourceManager.GetString("strInvalidConsumation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from can not be date from past..
        /// </summary>
        public static string strInvalidDateFrom {
            get {
                return ResourceManager.GetString("strInvalidDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be 18 years old to rent a car..
        /// </summary>
        public static string strInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("strInvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to must be later then date from..
        /// </summary>
        public static string strInvalidDates {
            get {
                return ResourceManager.GetString("strInvalidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid last name..
        /// </summary>
        public static string strInvalidLastName {
            get {
                return ResourceManager.GetString("strInvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid еmail..
        /// </summary>
        public static string strInvalidMail {
            get {
                return ResourceManager.GetString("strInvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid model..
        /// </summary>
        public static string strInvalidModel {
            get {
                return ResourceManager.GetString("strInvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid name..
        /// </summary>
        public static string strInvalidName {
            get {
                return ResourceManager.GetString("strInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid path..
        /// </summary>
        public static string strInvalidPath {
            get {
                return ResourceManager.GetString("strInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid phone..
        /// </summary>
        public static string strInvalidPhone {
            get {
                return ResourceManager.GetString("strInvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid price..
        /// </summary>
        public static string strInvalidPrice {
            get {
                return ResourceManager.GetString("strInvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid year..
        /// </summary>
        public static string strInvalidYear {
            get {
                return ResourceManager.GetString("strInvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string strLastName_ {
            get {
                return ResourceManager.GetString("strLastName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string strLocation_ {
            get {
                return ResourceManager.GetString("strLocation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string strModel_ {
            get {
                return ResourceManager.GetString("strModel:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /100 km..
        /// </summary>
        public static string strPerKm {
            get {
                return ResourceManager.GetString("strPerKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string strPersonalData {
            get {
                return ResourceManager.GetString("strPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string strPhone_ {
            get {
                return ResourceManager.GetString("strPhone:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up.
        /// </summary>
        public static string strPickUp {
            get {
                return ResourceManager.GetString("strPickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plovdiv.
        /// </summary>
        public static string strPlovdiv {
            get {
                return ResourceManager.GetString("strPlovdiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for .
        /// </summary>
        public static string strPricefor {
            get {
                return ResourceManager.GetString("strPricefor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per day:.
        /// </summary>
        public static string strPricePerDay_ {
            get {
                return ResourceManager.GetString("strPricePerDay:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent a car.
        /// </summary>
        public static string strRentACar {
            get {
                return ResourceManager.GetString("strRentACar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental period:.
        /// </summary>
        public static string strRentalPeriod {
            get {
                return ResourceManager.GetString("strRentalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Now.
        /// </summary>
        public static string strSearchNow {
            get {
                return ResourceManager.GetString("strSearchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seats..
        /// </summary>
        public static string strSeats {
            get {
                return ResourceManager.GetString("strSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Date.
        /// </summary>
        public static string strSelectDate {
            get {
                return ResourceManager.GetString("strSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofia.
        /// </summary>
        public static string strSofia {
            get {
                return ResourceManager.GetString("strSofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeful Reservation!.
        /// </summary>
        public static string strSuccesfulReservation {
            get {
                return ResourceManager.GetString("strSuccesfulReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price:.
        /// </summary>
        public static string strTotalPrice {
            get {
                return ResourceManager.GetString("strTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string strType_ {
            get {
                return ResourceManager.GetString("strType:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varna.
        /// </summary>
        public static string strVarna {
            get {
                return ResourceManager.GetString("strVarna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        public static string strYear_ {
            get {
                return ResourceManager.GetString("strYear:", resourceCulture);
            }
        }
    }
}
